- hosts: monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    grustnuy
  roles:
   - Update
   - monitoring
   - Grafana

  environment:
     http_proxy: http://devopsik.ru:8118
     https_proxy: http://devopsik.ru:8118